package io.github.projectbullethell.startscreenassets;

import com.badlogic.gdx.graphics.Color;

import java.util.ArrayList;

public class startText {
    ArrayList<Color> pixels;
    public startText(float r, float g, float b){
        pixels = new ArrayList<>();
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));

        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 254/255f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));

        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 254/255f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));

        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 254/255f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));

        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 254/255f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));

        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 254/255f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(1f, 1f, 1f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));

        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(64/255f, 64/255f, 64/255f, 4/255f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(0f, 0f, 0f, 0f));
        pixels.add(new Color(64/255f, 64/255f, 64/255f, 4/255f));
        pixels.add(new Color(0f, 0f, 0f, 1f));
    }

    public ArrayList<Color> getPixels() {
        return pixels;
    }
}
