app.version=1.0.0
app.id=JD.Project-BulleHell
ios.signing.identity=iPhone Developer
ios.team.id=4PZMFTF98D
app.mainclass=com.badlogic.bullethell.IOSLauncher
app.executable=IOSLauncher
app.build=1
app.name=Project-BulletHell IOS V
ios.sim.udid=B6AD6167-10B5-4BBD-9228-57CD4F41CFFB

